ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats do
    resources :cat_rental_requests, only: [:index]
  end

  resources :cat_rental_requests, only: [:new, :edit, :create, :destroy, :update, :show]
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
require 'date'
require 'active_support/core_ext/date'
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord

  validates :birth_date, :color, :name, :sex, :description, presence: true

  def age
    ((Date.today- birth_date).to_f/365).to_i
  end

  has_many :rental_requests, foreign_key: :cat_id, class_name: :CatRentalRequest
end

ninety_nine_cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED)}, presence: true
  validate :does_not_overlap_approved_request

  belongs_to :cat, dependent: :destroy

  def overlapping_requests
    # get a list of rental requests for this cat
    id = self.id || 0
    # other_requests = CatRentalRequest.find_by_sql(<<-SQL)
    #   SELECT *
    #   FROM cat_rental_requests AS a
    #   WHERE (
    #        '#{self.start_date}' BETWEEN a.start_date AND a.end_date
    #     OR '#{self.end_date}' BETWEEN a.start_date AND a.end_date
    #     OR ('#{self.start_date}' <= a.start_date AND '#{self.end_date}' >= a.end_date ) )
    #     AND a.id != #{id}
    # SQL

    CatRentalRequest
      .where("(? BETWEEN start_date AND end_date
         OR ? BETWEEN start_date AND end_date
         OR (? <= start_date AND ? >= end_date ) )
         AND id != ?", start_date, end_date, start_date, end_date, id)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists?
      self.errors[:start_date] << "This request overlaps with existing requests"
    end
  end

  def cat_name
    cat.name
  end
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    #@cat = Cat.find(params[:cat_id])
    @cat_rental_requests = CatRentalRequest.where(cat_id: params[:cat_id])
    render json: @cat_rental_requests
  end

  def show
    @cat_rental_request = CatRentalRequest.find(params[:id])
    render :show
  end

  def new
    @cats = Cat.all
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def edit
    @cats = Cat.all
    @cat_rental_request = CatRentalRequest.find(params[:id])
    render :edit
  end

  def update
    @cats = Cat.all
    @cat_rental_request = CatRentalRequest.find(params[:id])
    if @cat_rental_request.update(cat_rental_request_params)
      redirect_to cat_rental_request_url(@cat_rental_request)
    else
      render :edit
    end
  end

  def create
    @cats = Cat.all
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      redirect_to cat_rental_request_url(@cat_rental_request)
    else
      render :new
    end
  end

  private

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end

end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cat_rental_requests/_cat_rental_request.html.erb
<table>
  <thead>
    <tr>
      <th colspan="2"><a href="<%=cat_rental_request_url(cat_rental_request)%>"><%= cat_rental_request.cat_id %> </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="column">Start Date</td>
      <td class="col_val"><%= cat_rental_request.start_date %></td>
    </tr>
    <tr>
      <td class="column">End Date</td>
      <td class="col_val"><%= cat_rental_request.end_date %></td>
    </tr>
    <tr>
      <td class="column">Status </td>
      <td class="col_val"><%= cat_rental_request.status %></td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2">
        <a href="<%=edit_cat_rental_request_url(cat_rental_request)%>">Edit this kat request!</a>
      </td>
    </tr>
  </tfoot>
</table>

ninety_nine_cats/app/views/cat_rental_requests/_form.html.erb
<% if cat_rental_request.persisted? %>
  <% action_val = cat_rental_request_url(cat_rental_request) %>
  <% button_val = "Edit this kat rental request" %>
<% else %>
  <% action_val = cat_rental_requests_url %>
  <% button_val = "Create this kat rental request" %>
<% end %>

<form class="" action="<%=action_val%>" method="post">
  <% if cat_rental_request.persisted? %>
    <input type="hidden" name="_method" value="patch" >
  <% end %>
  <table>
    <tbody>
      <tr>
        <td class="column">
          <label for="cat_id">Cat</label>
        </td>
        <td class="col_val">
          <select class="" id="cat_id" name="cat_rental_request[cat_id]">
            <option value="" <%= cat_rental_request.id == "Blank" ? "selected" : "" %> >-- select a cat --</option>
            <% cats.each do |cat| %>
              <option value="<%= cat.id %> <%= cat_rental_request.cat_id == cat.id ? "selected" : "" %>">
                 <%=cat.name%>
               </option>
            <% end %>
          </select>
        </td>
      </tr>
      <tr>
        <td class="column">
          <label for="start_date"> Start Date </label>
        </td>
        <td class="col_val">
          <input type="date" id="start_date" name="cat_rental_request[start_date]" value="<%= cat_rental_request.start_date %>">
        </td>
      </tr>
      <tr>
        <td class="column">
          <label for="end_date"> End Date </label>
        </td>
        <td class="col_val">
          <input type="date" id="end_date" name="cat_rental_request[end_date]" value="<%= cat_rental_request.end_date %>">
        </td>
      </tr>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2">
          <input type="submit" name="submit_button" value="<%=button_val%>">
        </td>
      </tr>
    </tfoot>
  </table>

</form>

ninety_nine_cats/app/views/cat_rental_requests/edit.html.erb
<h1>Change that kat rental request!</h1>

<%= render 'form', cat_rental_request: @cat_rental_request, cats: @cats %>

ninety_nine_cats/app/views/cat_rental_requests/index.html.erb
<h1> Look at all these katz </h1>

<a href="<%=new_cat_url%>">Add a Kat!</a>
<br><br>

<% @cats.each do |cat| %>
  <%= render 'cat', cat: cat %>
  <br>
<% end %>

ninety_nine_cats/app/views/cat_rental_requests/new.html.erb
<h1>Make a new kat rental request!</h1>

<%= render 'form', cat_rental_request: @cat_rental_request, cats: @cats %>

ninety_nine_cats/app/views/cat_rental_requests/show.html.erb
<h1>This is a kat rental request!</h1>

<%= render 'cat_rental_request', cat_rental_request: @cat_rental_request %>
<br>
<!-- <a href="<%=cats_url%>">Index</a> -->

ninety_nine_cats/app/views/cats/_cat.html.erb
<table>
  <thead>
    <tr>
      <th colspan="2"><a href="<%=cat_url(cat)%>"><%= cat.name %> </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="column">Birth Date</td>
      <td class="col_val"><%= cat.birth_date %></td>
    </tr>
    <tr>
      <td class="column"> Pronoun </td>
      <td class="col_val"><%= cat.sex %></td>
    </tr>
    <tr>
      <td class="column"> Color </td>
      <td class="col_val"><%= cat.color %></td>
    </tr>
    <tr>
      <td class="column"> Description </td>
      <td class="col_val"><%= cat.description %></td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2">
        <a href="<%=edit_cat_url(cat)%>">Edit this kat!</a>
      </td>
    </tr>
  </tfoot>
</table>


<table>
  <thead>
    <tr>
      <th colspan="3">Rental Requests</th>
    </tr>
    <tr>
      <td >Start Date</th>
      <td >End Date</th>
      <td >Status</th>
    </tr>
  </thead>
  <tbody>
    <% cat.rental_requests.each do |request| %>
      <tr>
        <td class="col_val"><%= request.start_date %></td>
        <td class="col_val"><%= request.end_date %></td>
        <td class="col_val"><%= request.status %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2">
        <a href="<%=edit_cat_url(cat)%>">Edit this kat!</a>
      </td>
    </tr>
  </tfoot>
</table>

ninety_nine_cats/app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <% action_val = cat_url(cat) %>
  <% button_val = "Edit this kat" %>
<% else %>
  <% action_val = cats_url %>
  <% button_val = "Create this kat" %>
<% end %>

<form class="" action="<%=action_val%>" method="post">
  <% if cat.persisted? %>
    <input type="hidden" name="_method" value="patch" >
  <% end %>
  <table>
    <tbody>
      <tr>
        <th>
          <label for="name">Name</label>
        </th>
        <th>
          <input type="text" id="name" name="cat[name]" value="<%= cat.name %>">
        </th>
      </tr>
      <tr>
        <td class="column">
          <label for="birth_date"> Birth Date </label>
        </td>
        <td class="col_val">
          <input type="date" id="birth_date" name="cat[birth_date]" value="<%= cat.birth_date %>">
        </td>
      </tr>
      <tr>
        <td class="column">
          <label for="pronoun"> Pronoun </label>
        </td>
        <td class="col_val">

          <input type="radio" id="pronoun" name="cat[sex]" value="M"
            <%= cat.sex == "M" ? "checked" : "" %>
          >Male
          <input type="radio" id="pronoun" name="cat[sex]" value="F"
            <%= cat.sex == "F" ? "checked" : "" %>
          >Female
          <input type="radio" id="pronoun" name="cat[sex]" value="O"
            <%= cat.sex == "O" ? "checked" : "" %>
          >Other
        </td>
      </tr>
      <tr>
        <td class="column">
          <label for="color">Color</label>
        </td>
        <td class="col_val">
          <select class="" id="color" name="cat[color]">
            <option value="" <%= cat.color == "Blank" ? "selected" : "" %> >-- select a color --</option>
            <option value="Black" <%= cat.color == "Black" ? "selected" : "" %> >Black</option>
            <option value="White" <%= cat.color == "White" ? "selected" : "" %> >White</option>
            <option value="Gray" <%= cat.color == "Gray" ? "selected" : "" %> >Gray</option>
            <option value="Orange" <%= cat.color == "Orange" ? "selected" : "" %> >Orange</option>
            <option value="Blue" <%= cat.color == "Blue" ? "selected" : "" %> >Blue</option>
            <option value="Green" <%= cat.color == "Green" ? "selected" : "" %> >Green</option>
          </select>
        </td>
      </tr>
      <tr>
        <td class="column">
          <label for="description">
            Description
          </label>
        </td>
        <td class="col_val">
          <input type="textarea" id="description" name="cat[description]" value="<%= cat.description %>">
        </td>
      </tr>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2">
          <input type="submit" name="submit_button" value="<%=button_val%>">
        </td>
      </tr>
    </tfoot>
  </table>

</form>

ninety_nine_cats/app/views/cats/edit.html.erb
<h1>Change that kat!</h1>

<%= render 'form', cat: @cat %>

ninety_nine_cats/app/views/cats/index.html.erb
<h1> Look at all these katz </h1>

<% @cats.each do |cat| %>
  <%= render 'cat', cat: cat %>
  <br>
<% end %>

ninety_nine_cats/app/views/cats/new.html.erb
<h1>Make a new kat!</h1>

<%= render 'form', cat: @cat %>

ninety_nine_cats/app/views/cats/show.html.erb
<h1>This is a cat!</h1>

<%= render 'cat', cat: @cat %>
<br>
<a href="<%=cats_url%>">Index</a>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <link href="/assets/stylesheets/style.css" type="text/css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>